/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 29-mar.-2020 10:03:13 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS Banco CASCADE
;

DROP TABLE IF EXISTS Corresponsal CASCADE
;

DROP TABLE IF EXISTS Negociacion CASCADE
;

DROP TABLE IF EXISTS Pais CASCADE
;

DROP TABLE IF EXISTS Referencia CASCADE
;

/* Create Tables */

CREATE TABLE Banco
(
	id_banco varchar(20) NOT NULL,
	nombre varchar(50) NULL,
	sede varchar(50) NULL,
	numero_cuenta varchar(50) NULL,
	id_comision varchar(50) NULL,
	id_pais varchar(50) NULL
)
;

CREATE TABLE Corresponsal
(
	id_corresponsal varchar(50) NOT NULL,
	id_banco varchar(20) NULL
)
;

CREATE TABLE Negociacion
(
	id_comision varchar(50) NOT NULL,
	origen varchar(50) NULL,
	vigencia_giro varchar(50) NULL,
	flete varchar(50) NULL,
	id_transacion varchar(50) NOT NULL,
	hora_fecha varchar(50) NULL,
	id_banco varchar(20) NULL
)
;

CREATE TABLE Pais
(
	id_pais varchar(50) NOT NULL,
	nombre_pais varchar(50) NULL
)
;

CREATE TABLE Referencia
(
	id_giro varchar(50) NOT NULL,
	documento_legal varchar(50) NULL,
	receptor varchar(50) NULL,
	destinario varchar(50) NULL,
	id_banco varchar(20) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Banco ADD CONSTRAINT PK_Banco
	PRIMARY KEY (id_banco)
;

CREATE INDEX IXFK_Banco_Negociacion ON Banco (id_comision ASC)
;

CREATE INDEX IXFK_Banco_Pais ON Banco (id_pais ASC)
;

ALTER TABLE Corresponsal ADD CONSTRAINT PK_Corresponsal
	PRIMARY KEY (id_corresponsal)
;

CREATE INDEX IXFK_Corresponsal_Banco ON Corresponsal (id_banco ASC)
;

ALTER TABLE Negociacion ADD CONSTRAINT PK_Negociacion
	PRIMARY KEY (id_comision)
;

CREATE INDEX IXFK_Negociacion_Banco ON Negociacion (id_banco ASC)
;

ALTER TABLE Pais ADD CONSTRAINT PK_Pais
	PRIMARY KEY (id_pais)
;

ALTER TABLE Referencia ADD CONSTRAINT PK_Refrencia
	PRIMARY KEY (id_giro)
;

CREATE INDEX IXFK_Referencia_Banco ON Referencia (id_banco ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE Banco ADD CONSTRAINT FK_Banco_Pais
	FOREIGN KEY (id_pais) REFERENCES Pais (id_pais) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Corresponsal ADD CONSTRAINT FK_Corresponsal_Banco
	FOREIGN KEY (id_banco) REFERENCES Banco (id_banco) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Negociacion ADD CONSTRAINT FK_Negociacion_Banco
	FOREIGN KEY (id_banco) REFERENCES Banco (id_banco) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Referencia ADD CONSTRAINT FK_Referencia_Banco
	FOREIGN KEY (id_banco) REFERENCES Banco (id_banco) ON DELETE Restrict ON UPDATE Restrict
;
